---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: Copy file to destination
      copy:
        src: /tmp/index.html
        dest: /tmp/devops/ansible-practice
